spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/storedproducer
#    username: root
#    password: admin
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 8082
